import Head from "next/head";
import { useEffect } from "react";

export default function Home() {
  useEffect(() => {
    const productGallery = cloudinary.galleryWidget({
      container: "#video-gallery",
      cloudName: "nefejames",
      mediaAssets: [
        { tag: "dog-picture", mediaType: "image" }, //while we explicity set the media type for the dog-picture tag to image, we don't need to do tyhat because the default mediaType for all media assets is 'iamge'
        { tag: "dog-video", mediaType: "video" },
      ],
    });

    productGallery.render();
  }, []);

  return (
    <div className="container">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1>Ecommerce Product Video Gallery</h1>

      <div className="gallery-container">
        <div id="video-gallery"></div>
      </div>
    </div>
  );
}
